project:
  type: website
  output-dir: _site
  resources: 
    - "!offline_pdfs/" 
  post-render: manage_pdfs.R

website:
  page-navigation: true
  title: "CSCI 2025"
  description: "Homepage for CSCI 2025 - Data Manipulation and Visualization at the College of Idaho, Winter 2026."
  site-url: "https://csci2025wi26.netlify.app/"

  repo-url: https://github.com/csci2025-wi26/csci2025-wi26
  repo-actions: [edit, issue]

  sidebar:
    background: "#533860" # Coyote Purple
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/csci2025-wi26
        text: "GitHub organization"
      - icon: person-fill
        href: https://cofi.instructure.com/courses/18429
        text: "Canvas course"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing/computing-access.qmd
            text: Access
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Projects"
        contents:
          # - href: project/project-1.qmd
          # - href: project/project-2.qmd
          # - href: project/project-tips-resources.qmd
          #   text: Tips + resources
      - section: "HW"
        contents:
          # - href: hw/hw-0.qmd
          #   text: HW 0
          # - href: hw/hw-1.qmd
          #   text: HW 1
          # - href: hw/hw-2.qmd
          #   text: HW 2
          # - href: hw/hw-3.qmd
          #   text: HW 3            
          # - href: hw/hw-4.qmd
          #   text: HW 4
          # - href: hw/hw-5.qmd
          #   text: HW 5 
          # - href: hw/hw-6.qmd
          #   text: HW 6 
      - section: "Student work"
        contents:
          # - href: student-work/thank-you.qmd
          #   text: Thank you cards
          # - href: student-work/ugly-plot.qmd
          #   text: Ugly plots
          # - href: student-work/project-1.qmd
          #   text: Project 1
          # - href: student-work/project-2.qmd
          #   text: Project 2
          
  page-footer:
    right: "This page is built with ðŸ’› and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Eric Friedlander"
    background: "#533860" # Goldenrod
    
format:
  html:
    theme:
      light: [cosmo, style/csci2025.scss]
      dark: [cosmo, style/csci2025.scss, style/dark.scss]
    linkcolor: "#533860" # Coyote Purple
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark
    code-link: true

execute:
  freeze: auto

editor: visual
